"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.files.storage import FileSystemStorage
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-insecure-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    "127.0.0.1", "localhost",
    "tupcosa.online", ".tupcosa.online",
    ".onrender.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://tupcosa.online",
    "https://app.tupcosa.online",
    "https://*.onrender.com",
    "https://www.tupcosa.online",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR/'myapp/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.user_role_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {}
DATABASES = {}
db_url = os.getenv("DATABASE_URL")

if db_url:
    # Cloud DB (Render, etc.)
    DATABASES["default"] = dj_database_url.config(conn_max_age=600, ssl_require=True)
elif DEBUG:
    # Local dev DB (use the one that already has your data)
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "osasystemdb",
        "USER": "osathesis",
        "PASSWORD": "osathesis25",
        "HOST": "localhost",
        "PORT": "3306",
    }
else:
    # Fallback only when NOT debug and no DATABASE_URL
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }

# Keep security flags separate from DB selection:
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
GMF_TEMPLATE_PATH = BASE_DIR / "myapp" / "cert_templates" / "good-moral-form.xlsx"
TIME_ZONE = "Asia/Manila"

if os.name == "nt":
    # 1) LibreOffice's Python (needed for UNO imports in your script)
    DEFAULT_LO_PY = r"C:\Program Files\LibreOffice\program\python.exe"

    # 2) CLI binary (handy if you ever call soffice directly)
    win_soffice = r"C:\Program Files\LibreOffice\program\soffice.com"
    if not Path(win_soffice).exists():
        win_soffice = r"C:\Program Files\LibreOffice\program\soffice.exe"
    DEFAULT_SOFFICE = win_soffice
else:
    DEFAULT_LO_PY = None          # leave unset on Render unless installed via Docker
    DEFAULT_SOFFICE = None

LIBREOFFICE_PY  = os.getenv("LIBREOFFICE_PY", DEFAULT_LO_PY)
LIBREOFFICE_BIN = os.getenv("LIBREOFFICE_BIN", DEFAULT_SOFFICE)
LIBREOFFICE_PATH = LIBREOFFICE_BIN  # alias if your code references this

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = [BASE_DIR / "myapp" / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)


DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
MEDIA_URL  = '/media/'
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", Path(BASE_DIR) / "media"))
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)