# Generated by Django 5.1.1 on 2025-06-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('evidence_img1', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('evidence_img2', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('date_time', models.DateTimeField()),
                ('secu_on_shft', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('approval', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('new_time_of_record', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='myapp.student')),
            ],
        ),
    ]
