# Generated by Django 5.1.1 on 2025-06-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_record',
        ),
    ]
