# Generated by Django 5.1.1 on 2025-06-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='tupc_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
