# Generated by Django 5.1.1 on 2025-06-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20250627_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('tupc_id', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Senators', 'Senators'), ('Governors', 'Governors')], max_length=20)),
                ('photo', models.ImageField(upload_to='candidate_photos/')),
            ],
        ),
    ]
