# Generated by Django 5.1.1 on 2025-06-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_candidate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='candidate',
        ),
    ]
