# Generated by Django 5.1.1 on 2025-06-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_candidate_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Senator', 'Senator'), ('Governor', 'Governor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tupc_id',
            field=models.CharField(max_length=40),
        ),
    ]
