# Generated by Django 5.1.1 on 2025-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_candidate_position_alter_candidate_tupc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('extension_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('student_id', models.CharField(max_length=20)),
                ('program_course', models.CharField(blank=True, max_length=100)),
                ('violation_date', models.DateField()),
                ('violation_time', models.TimeField()),
                ('violation_type', models.CharField(choices=[('During Class Hours', 'During Class Hours'), ('Not Wearing Proper Uniform and ID', 'Not Wearing Proper Uniform and ID'), ('Cross Dressing in Uniform and Wash Days', 'Cross Dressing in Uniform and Wash Days'), ('Unwanted Facial Hair', 'Unwanted Facial Hair'), ('Wearing of Earrings or Multiple Earrings', 'Wearing of Earrings or Multiple Earrings'), ('Wearing Caps or Hats Inside', 'Wearing Caps or Hats Inside'), ('Entering Classrooms without Permission from Instructor', 'Entering Classrooms without Permission from Instructor'), ('Leaving Classrooms without Permission from Instructor', 'Leaving Classrooms without Permission from Instructor'), ('Attempting to Join a Fraternity', 'Attempting to Join a Fraternity'), ('Unauthorized Posting Printed Materials', 'Unauthorized Posting Printed Materials'), ('Unauthorized Use of University Facilities', 'Unauthorized Use of University Facilities'), ('Unauthorized Removal of Notices/Posters', 'Unauthorized Removal of Notices/Posters'), ('Possession of Gambling Paraphernalia', 'Possession of Gambling Paraphernalia'), ('Unauthorized Devices during Class', 'Unauthorized Devices during Class'), ('Irresponsible Use of Water/Electricity', 'Irresponsible Use of Water/Electricity'), ('Lewd Gestures/Lustful Words to Student', 'Lewd Gestures/Lustful Words to Student'), ('Accidental University Property Damage', 'Accidental University Property Damage'), ('Public Display of Affection', 'Public Display of Affection'), ('Possession of Cigarette or Tobacco', 'Possession of Cigarette or Tobacco')], max_length=150)),
                ('guard_name', models.CharField(max_length=100)),
                ('evidence_1', models.ImageField(upload_to='evidence/')),
                ('evidence_2', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='myapp_viola_status_574ee0_idx')],
            },
        ),
    ]
