# Generated by Django 5.1.1 on 2025-07-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_violation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='violation',
            name='myapp_viola_status_574ee0_idx',
        ),
        migrations.AlterModelTable(
            name='violation',
            table='violation',
        ),
    ]
