# Generated by Django 5.1.1 on 2025-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_violation_myapp_viola_status_574ee0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='violation',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='violation',
            name='program_course',
            field=models.CharField(max_length=100),
        ),
    ]
