# Generated by Django 5.1.1 on 2025-07-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_violation_first_name_alter_violation_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('Disturbance', 'Causing Disturbance During Class Hours'), ('Proper Uniform', 'Not Wearing Proper Uniform and ID'), ('Cross Dressing', 'Cross Dressing in Uniform and Wash Days'), ('Facial Hair', 'Unwanted Facial Hair'), ('Earrings', 'Wearing of Earrings or Multiple Earrings'), ('Caps', 'Wearing of Caps or Hats inside Covered Facilities'), ('Entering Classroom', 'Entering Classrooms without Permission from Instructor'), ('Leaving Classroom', 'Leaving Classrooms without Permission from Instructor'), ('Attempt Fraternity', 'Attempting to Join a Fraternity'), ('Posting Materials', 'Unauthorized Posting Printed Materials'), ('Use of University Facilities', 'Unauthorized Use of University Facilities'), ('Official Notices', 'Unauthorized Removal of Official Notices and Posters'), ('Gambling', 'Possession of Gambling Paraphernalia'), ('Devices', 'Unauthorized Use of Devices during Class'), ('Resources', 'Irresponsible Use of Water and Electricity within University'), ('Harrassment', 'Making Lewd Gestures and Lustful Words to a Student'), ('Property Damage', 'Accidental Damage of University Property'), ('PDA', 'Public Display of Physical Intimacy or Affection'), ('Cigarette', 'Possession of Any type of Cigarette or Tobacco inside University')], max_length=150),
        ),
    ]
