# Generated by Django 5.1.1 on 2025-07-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_violation_violation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Internal', 'Internal'), ('External Govt', 'External (Govt)'), ('External Private', 'External (Private)')], max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('deadline_date', models.DateField()),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='scholarship_attachments/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='scholarship_attachments/')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='scholarship_attachments/')),
                ('attachment_4', models.FileField(blank=True, null=True, upload_to='scholarship_attachments/')),
                ('attachment_5', models.FileField(blank=True, null=True, upload_to='scholarship_attachments/')),
            ],
            options={
                'db_table': 'scholarship',
            },
        ),
    ]
