# Generated by Django 5.1.1 on 2025-07-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lostandfound_images/')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lostandfound',
            },
        ),
    ]
