# Generated by Django 5.1.1 on 2025-07-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_goodmoralrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodmoralrequest',
            name='upload_ack_receipt',
        ),
        migrations.RemoveField(
            model_name='goodmoralrequest',
            name='upload_diploma',
        ),
        migrations.RemoveField(
            model_name='goodmoralrequest',
            name='upload_id',
        ),
        migrations.AddField(
            model_name='goodmoralrequest',
            name='document_type',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='goodmoralrequest',
            name='uploaded_file',
            field=models.FileField(default='uploads/goodmoral/default.pdf', upload_to='uploads/goodmoral/'),
        ),
    ]
