# Generated by Django 5.1.1 on 2025-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_goodmoralrequest_upload_ack_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssistantshipRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Requirements Text')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'studentassistant',
            },
        ),
    ]
