# Generated by Django 5.1.1 on 2025-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_studentassistantshiprequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACSORequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acso',
            },
        ),
    ]
