# Generated by Django 5.1.1 on 2025-08-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_acsorequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmoralrequest',
            name='other_purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
