# Generated by Django 5.1.1 on 2025-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_goodmoralrequest_other_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='date_graduated',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
    ]
