# Generated by Django 5.1.1 on 2025-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_goodmoralrequest_date_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='date_admission',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='date_graduated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
