# Generated by Django 5.1.1 on 2025-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_goodmoralrequest_date_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmoralrequest',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/goodmoral/certificates/'),
        ),
    ]
