# Generated by Django 5.1.1 on 2025-08-10 13:23

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_goodmoralrequest_certificate_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDSurrenderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('Dropped', 'Dropped'), ('Graduate', 'Graduate'), ('Transfer', 'Transfer'), ('Withdrawn', 'Withdrawn'), ('Claim of Credentials', 'Claim of Credentials'), ('Worn Out', 'Worn Out')], max_length=30)),
                ('student_number', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator('^TUPC-\\d{2}-\\d{4}$', message='Use TUPC-XX-XXXX (e.g., TUPC-23-0123). Adjust regex if your format differs.')])),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ('Graduate', 'Graduate')], max_length=12)),
                ('inclusive_years', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}$', message='Use YYYY-YYYY (e.g., 2019-2023).')])),
                ('upload_id_front', models.FileField(upload_to='surrender_ids/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), myapp.models.validate_file_size])),
                ('upload_id_back', models.FileField(upload_to='surrender_ids/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), myapp.models.validate_file_size])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=8)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'ID Surrender Request',
                'verbose_name_plural': 'ID Surrender Requests',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='myapp_idsur_status_ca2e2e_idx')],
            },
        ),
    ]
