# Generated by Django 5.1.1 on 2025-08-10 13:30

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_idsurrenderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsurrenderrequest',
            name='acknowledgement_receipt',
            field=models.FileField(blank=True, null=True, upload_to='surrender_ids/receipts/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf']), myapp.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='idsurrenderrequest',
            name='student_number',
            field=models.CharField(max_length=13),
        ),
    ]
