# Generated by Django 5.1.1 on 2025-08-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_idsurrenderrequest_acknowledgement_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idsurrenderrequest',
            name='student_number',
            field=models.CharField(max_length=18),
        ),
    ]
