# Generated by Django 5.1.1 on 2025-08-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_idsurrenderrequest_student_number'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idsurrenderrequest',
            new_name='Surrender_I_status_03e4f7_idx',
            old_name='myapp_idsur_status_ca2e2e_idx',
        ),
        migrations.AddField(
            model_name='idsurrenderrequest',
            name='contact_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterModelTable(
            name='idsurrenderrequest',
            table='Surrender_ID',
        ),
    ]
