# Generated by Django 5.1.1 on 2025-08-11 07:53

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_rename_myapp_idsur_status_ca2e2e_idx_surrender_i_status_03e4f7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsurrenderrequest',
            name='document_type',
            field=models.CharField(choices=[('id', 'School ID'), ('affidavit', 'Affidavit of Loss')], db_index=True, default='id', max_length=16),
        ),
        migrations.AlterField(
            model_name='idsurrenderrequest',
            name='student_number',
            field=models.CharField(db_index=True, max_length=18, validators=[django.core.validators.RegexValidator('^TUPC-\\d{2}-\\d{4,10}$', message='Format: TUPC-XX-XXXX up to TUPC-XX-XXXXXXXXXX.')]),
        ),
        migrations.AlterField(
            model_name='idsurrenderrequest',
            name='upload_id_back',
            field=models.FileField(blank=True, null=True, upload_to='surrender_ids/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), myapp.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='idsurrenderrequest',
            name='upload_id_front',
            field=models.FileField(blank=True, null=True, upload_to='surrender_ids/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), myapp.models.validate_file_size]),
        ),
    ]
