# Generated by Django 5.1.1 on 2025-08-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_idsurrenderrequest_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodmoralrequest',
            name='certificate_pdf',
        ),
    ]
