# Generated by Django 5.1.1 on 2025-08-15 08:49

import django.db.models.deletion
import django.db.models.functions.datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_goodmoralrequest_certificate_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityServiceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=20)),
                ('total_required_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('hours_completed', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'community_service_case',
                'indexes': [models.Index(fields=['student_id', 'is_closed'], name='community_s_student_30f42b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunityServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('is_official', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='myapp.communityservicecase')),
            ],
            options={
                'db_table': 'community_service_log',
            },
        ),
    ]
