# Generated by Django 5.1.1 on 2025-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_communityservicecase_communityservicelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationsettlement',
            name='violation',
        ),
        migrations.AddField(
            model_name='violation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='violation',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='violation',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='settlement_type',
            field=models.CharField(choices=[('None', 'None'), ('Apology Letter', 'Apology Letter'), ('Community Service', 'Community Service')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='violation',
            name='severity',
            field=models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major')], default='MINOR', max_length=5),
        ),
        migrations.AlterField(
            model_name='violation',
            name='student_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['status'], name='violation_status_84b470_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['student_id', 'status'], name='violation_student_e006bb_idx'),
        ),
        migrations.DeleteModel(
            name='ViolationSettlement',
        ),
    ]
