# Generated by Django 5.1.1 on 2025-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_violationsettlement_violation_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communityservicelog',
            index=models.Index(fields=['case', 'check_out_at'], name='community_s_case_id_5d132d_idx'),
        ),
    ]
