# Generated by Django 5.1.1 on 2025-08-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_communityservicelog_community_s_case_id_5d132d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityservicecase',
            name='extension_name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='communityservicecase',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='communityservicecase',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='communityservicecase',
            name='middle_initial',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='communityservicecase',
            name='program_course',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='communityservicecase',
            index=models.Index(fields=['last_name', 'first_name'], name='community_s_last_na_025522_idx'),
        ),
    ]
