# Generated by Django 5.1.1 on 2025-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_violation_violation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='evidence_1',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
