# Generated by Django 5.1.1 on 2025-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_violation_evidence_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/goodmoral/'),
        ),
    ]
