# Generated by Django 5.1.1 on 2025-08-25 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_goodmoralrequest_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('extension', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly in the format: +63 XXXXXXXXXX (10 digits after a space).', regex='^\\+63\\s\\d{10}$')])),
                ('student_number', models.CharField(max_length=23, validators=[django.core.validators.RegexValidator(message='Student number must match TUPC-XX-XXXXXXXXXX… (10–15 digits at the end).', regex='^TUPC-[A-Z0-9]{2}-\\d{10,15}$')])),
                ('program', models.CharField(max_length=100)),
                ('year_level', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year'), ('Fifth Year', 'Fifth Year')], max_length=20)),
                ('client_type', models.CharField(choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government (Employee/Agency)', 'Government (Employee/Agency)')], max_length=50)),
                ('stakeholder', models.CharField(choices=[('TUPC Student', 'TUPC Student'), ('Alumnus', 'Alumnus'), ('Student from other School', 'Student from other School'), ('External Client', 'External Client'), ('Parent/Guardian', 'Parent/Guardian'), ('TUPC Employee', 'TUPC Employee')], max_length=50)),
                ('purpose', models.CharField(choices=[('Credentials', 'Credentials'), ('Application of Graduation', 'Application of Graduation'), ('Employment', 'Employment'), ('Continuing Education', 'Continuing Education'), ('Transfer', 'Transfer'), ('Dismissal', 'Dismissal')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['student_number'], name='myapp_clear_student_67daa1_idx'), models.Index(fields=['created_at'], name='myapp_clear_created_1ffe7f_idx')],
            },
        ),
    ]
