# Generated by Django 5.1.1 on 2025-08-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_clearancerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearancerequest',
            options={'verbose_name': 'Clearance', 'verbose_name_plural': 'Clearance Requests'},
        ),
        migrations.RenameIndex(
            model_name='clearancerequest',
            new_name='Clearance_student_1728a1_idx',
            old_name='myapp_clear_student_67daa1_idx',
        ),
        migrations.RenameIndex(
            model_name='clearancerequest',
            new_name='Clearance_created_785e10_idx',
            old_name='myapp_clear_created_1ffe7f_idx',
        ),
        migrations.AlterModelTable(
            name='clearancerequest',
            table='Clearance',
        ),
    ]
