# Generated by Django 5.1.1 on 2025-08-25 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_clearancerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancerequest',
            name='student_number',
            field=models.CharField(max_length=23, validators=[django.core.validators.RegexValidator(message='Student number must match TUPC-XX-XXXXXXXX (4–10 digits at the end).', regex='^TUPC-[A-Z0-9]{2}-\\d{4,10}$')]),
        ),
    ]
