# Generated by Django 5.1.1 on 2025-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_clearancerequest_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancerequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
