# Generated by Django 5.1.1 on 2025-08-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_clearancerequest_middle_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goodmoralrequest',
            index=models.Index(fields=['is_approved', 'submitted_at'], name='goodmoral_is_appr_e1945d_idx'),
        ),
    ]
