# Generated by Django 5.1.1 on 2025-09-01 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_goodmoralrequest_goodmoral_is_appr_e1945d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(db_index=True, help_text='Format: NN-NNN (e.g., 12-345)', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Use format NN-NNN (e.g., 12-345). Only digits with a hyphen.', regex='^\\d{2}-\\d{3}$')])),
                ('full_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitators_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Facilitator',
                'ordering': ['full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('faculty_id__regex', '^\\d{2}-\\d{3}$')), name='faculty_id_nn_nnn_format')],
            },
        ),
    ]
