# Generated by Django 5.1.1 on 2025-09-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_facilitator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guard', 'Security Guard'), ('scholarship', 'Scholarship Coordinator'), ('staff', 'Office Staff'), ('sa', 'Student Assistant')], max_length=20),
        ),
    ]
