# Generated by Django 5.1.1 on 2025-09-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_delete_candidate_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
