# Generated by Django 5.1.1 on 2025-09-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_facilitator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guard', 'Security Guard'), ('scholarship', 'Scholarship Coordinator'), ('staff', 'Office Staff'), ('studasst', 'Student Assistant')], max_length=20),
        ),
    ]
