# Generated by Django 5.1.1 on 2025-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_communityservicelog_facilitator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
