# Generated by Django 5.1.1 on 2025-09-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_otpverification_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityservicelog',
            name='facilitator',
        ),
        migrations.AddField(
            model_name='communityservicelog',
            name='facilitator_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='communityservicelog',
            name='facilitator_source',
            field=models.CharField(blank=True, choices=[('admin', 'AdminUser'), ('faculty', 'Faculty')], default='', max_length=12),
        ),
    ]
