# Generated by Django 5.1.1 on 2025-09-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_alter_violation_violation_type'),
        ('myapp', '0052_remove_communityservicelog_facilitator_and_more'),
    ]

    operations = [
    ]
