# Generated by Django 5.1.1 on 2025-09-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('academic_year', models.CharField(max_length=9)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_finalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EligibleVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32)),
                ('is_eligible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibles', to='myapp.election')),
            ],
            options={
                'indexes': [models.Index(fields=['election', 'student_id'], name='myapp_eligi_electio_53ced6_idx')],
                'unique_together': {('election', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_student_id', models.CharField(max_length=32)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='myapp.election')),
            ],
            options={
                'indexes': [models.Index(fields=['election', 'voter_student_id'], name='myapp_vote_electio_cb7a93_idx')],
                'unique_together': {('election', 'voter_student_id')},
            },
        ),
    ]
