# Generated by Django 5.1.1 on 2025-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_election_eligiblevoter_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_at',
            field=models.DateField(),
        ),
    ]
