# Generated by Django 5.1.1 on 2025-09-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_alter_election_end_at_alter_election_start_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='end_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='start_at',
            new_name='start_date',
        ),
    ]
