# Generated by Django 5.1.1 on 2025-09-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_rename_end_at_election_end_date_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eligiblevoter',
            new_name='EligibleVot_electio_931c2d_idx',
            old_name='myapp_eligi_electio_53ced6_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='Vote_electio_fdcc30_idx',
            old_name='myapp_vote_electio_cb7a93_idx',
        ),
        migrations.AlterModelTable(
            name='election',
            table='Election',
        ),
        migrations.AlterModelTable(
            name='eligiblevoter',
            table='EligibleVoter',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='Vote',
        ),
    ]
