# Generated by Django 5.1.1 on 2025-09-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_rename_myapp_eligi_electio_53ced6_idx_eligiblevot_electio_931c2d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_finalized',
        ),
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed'), ('finalized', 'Finalized')], default='scheduled', max_length=20),
        ),
    ]
