# Generated by Django 5.1.1 on 2025-09-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_remove_election_is_finalized_election_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
