# Generated by Django 5.1.1 on 2025-09-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_election_is_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('tupc_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Senator', 'Senator'), ('Governor', 'Governor')], max_length=32)),
                ('party', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(upload_to='candidates/')),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='myapp.election')),
            ],
            options={
                'db_table': 'Candidate',
                'indexes': [models.Index(fields=['election', 'position'], name='Candidate_electio_9c8144_idx'), models.Index(fields=['election', 'tupc_id'], name='Candidate_electio_8e50c7_idx'), models.Index(fields=['academic_year'], name='Candidate_academi_ab3354_idx'), models.Index(fields=['party'], name='Candidate_party_b0a87a_idx')],
                'unique_together': {('election', 'tupc_id', 'position')},
            },
        ),
    ]
