# Generated by Django 5.1.1 on 2025-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ballot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vote',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
