# Generated by Django 5.1.1 on 2025-09-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_vote_ballot_vote_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='ballot',
            field=models.JSONField(default=dict),
        ),
    ]
