# Generated by Django 5.1.1 on 2025-09-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_alter_vote_ballot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guard', 'Security Guard'), ('scholarship', 'Scholarship Coordinator'), ('staff', 'Staff'), ('studasst', 'Student Assistant'), ('comselec', 'Comselec')], max_length=20),
        ),
    ]
