# Generated by Django 5.1.1 on 2025-09-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsurrenderrequest',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
