# Generated by Django 5.1.1 on 2025-09-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_idsurrenderrequest_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('finalized', 'Finalized')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status'], name='Election_status_625f43_idx'),
        ),
        migrations.AddConstraint(
            model_name='election',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='only_one_active_election'),
        ),
    ]
