# Generated by Django 5.1.1 on 2025-10-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_alter_election_status_alter_vote_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityservicecase',
            name='sdt_resolution_no',
            field=models.CharField(blank=True, default='', help_text='Resolution number from the Student Disciplinary/Tribunal converting a major case to community service.', max_length=64, verbose_name='SDT Resolution No.'),
        ),
        migrations.AddIndex(
            model_name='communityservicecase',
            index=models.Index(fields=['sdt_resolution_no'], name='community_s_sdt_res_98f1a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityservicecase',
            constraint=models.UniqueConstraint(condition=models.Q(('sdt_resolution_no', ''), _negated=True), fields=('sdt_resolution_no',), name='uniq_sdt_resolution_no_when_present'),
        ),
    ]
