# Generated by Django 5.1.1 on 2025-10-05 14:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_communityservicecase_sdt_resolution_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityServiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='myapp.communityservicecase')),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cs_adjustment', to='myapp.violation')),
            ],
            options={
                'db_table': 'community_service_adjustment',
                'indexes': [models.Index(fields=['case'], name='community_s_case_id_bfd365_idx')],
            },
        ),
    ]
