# Generated by Django 5.1.1 on 2025-10-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_communityserviceadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
