# Generated by Django 5.1.1 on 2025-10-23 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_useraccount_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancerequest',
            name='student_number',
            field=models.CharField(max_length=23, validators=[django.core.validators.RegexValidator(message='Student number must match TUPC-XX-XXXXXXXX (4–15 digits at the end).', regex='^TUPC-\\d{2}-[A-Za-z0-9]{4,15}$')]),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='student_id',
            field=models.CharField(max_length=23),
        ),
        migrations.AlterField(
            model_name='idsurrenderrequest',
            name='student_number',
            field=models.CharField(db_index=True, max_length=23, validators=[django.core.validators.RegexValidator('^TUPC-\\d{2}-[A-Za-z0-9]{4,15}$', message='Format: TUPC-XX-XXXX up to TUPC-XX-XXXXXXXXXX.')]),
        ),
    ]
