# Generated by Django 5.1.1 on 2025-11-04 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_alter_violation_violation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityservicelog',
            name='facilitator_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_logs_operated', to='myapp.facilitator'),
        ),
        migrations.AddField(
            model_name='communityservicelog',
            name='facilitator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_logs_operated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='violation',
            name='settlement_type',
            field=models.CharField(choices=[('None', 'None'), ('Apology Letter', 'Apology Letter'), ('Community Service', 'Community Service'), ('SDT Settlement', 'SDT Settlement')], default='None', max_length=50),
        ),
        migrations.AddIndex(
            model_name='communityservicelog',
            index=models.Index(fields=['facilitator_user', 'check_out_at'], name='community_s_facilit_e4e593_idx'),
        ),
        migrations.AddIndex(
            model_name='communityservicelog',
            index=models.Index(fields=['facilitator_faculty', 'check_out_at'], name='community_s_facilit_2adb8d_idx'),
        ),
    ]
