# Generated by Django 5.1.1 on 2025-11-05 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_clearancerequest_address_clearancerequest_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancerequest',
            name='contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use +63 XXX-XXX-XXXX.', regex='^\\+63\\s(?:\\d{3}-\\d{3}-\\d{4}|\\d{10})$')]),
        ),
    ]
