# Generated by Django 5.1.1 on 2025-11-05 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_alter_clearancerequest_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsurrenderrequest',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Format: +63-XXX-XXX-XXXX', max_length=17, null=True, validators=[django.core.validators.RegexValidator('^\\+63-\\d{3}-\\d{3}-\\d{4}$', message='Use +63-XXX-XXX-XXXX (e.g., +63-912-345-6789).')]),
        ),
    ]
