# Generated by Django 5.1.1 on 2025-11-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_idsurrenderrequest_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmoralrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goodmoralrequest',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
