# Generated by Django 5.1.1 on 2025-11-06 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_goodmoralrequest_address_goodmoralrequest_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmoralrequest',
            name='client_type',
            field=models.CharField(blank=True, choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government (Employee/Agency)', 'Government (Employee/Agency)')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='goodmoralrequest',
            name='stakeholder',
            field=models.CharField(blank=True, choices=[('TUPC Student', 'TUPC Student'), ('Alumnus', 'Alumnus'), ('Student from other School', 'Student from other School'), ('External Client', 'External Client'), ('Parent/Guardian', 'Parent/Guardian'), ('TUPC Employee', 'TUPC Employee')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='goodmoralrequest',
            name='uploaded_file_2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/goodmoral/'),
        ),
        migrations.AlterField(
            model_name='clearancerequest',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(121)]),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='requester_contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use +63 XXX-XXX-XXXX.', regex='^\\+63\\s(?:\\d{3}-\\d{3}-\\d{4}|\\d{10})$')]),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True),
        ),
    ]
