# Generated by Django 5.1.1 on 2025-11-06 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_goodmoralrequest_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsurrenderrequest',
            name='client_type',
            field=models.CharField(blank=True, choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government (Employee/Agency)', 'Government (Employee/Agency)')], db_index=True, help_text='Required on new submissions.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='idsurrenderrequest',
            name='stakeholder',
            field=models.CharField(blank=True, choices=[('TUPC Student', 'TUPC Student'), ('Alumnus', 'Alumnus'), ('Student from other School', 'Student from other School'), ('External Client', 'External Client'), ('Parent/Guardian', 'Parent/Guardian'), ('TUPC Employee', 'TUPC Employee')], db_index=True, help_text='Required on new submissions.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='document_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='requester_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='idsurrenderrequest',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Age in years (16–121).', null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(121)]),
        ),
        migrations.AddIndex(
            model_name='idsurrenderrequest',
            index=models.Index(fields=['client_type'], name='Surrender_I_client__cec493_idx'),
        ),
        migrations.AddIndex(
            model_name='idsurrenderrequest',
            index=models.Index(fields=['stakeholder'], name='Surrender_I_stakeho_8a037d_idx'),
        ),
    ]
