# Generated by Django 5.1.1 on 2025-11-06 12:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_idsurrenderrequest_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guard', 'Security Guard'), ('scholarship', 'Scholarship Coordinator'), ('staff', 'Staff'), ('studasst', 'Student Assistant'), ('comselec', 'Comselec'), ('studlife', 'Student Life Development Coordinator'), ('superadmin', 'Adviser-Superadmin')], max_length=20),
        ),
    ]
    

