# Generated by Django 5.1.1 on 2025-11-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0082_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('Disturbance', 'Loitering or Causing Disturbance During Class Hours'), ('Proper Uniform', 'Not Wearing Proper Uniform and ID / Haircut / Haircolor'), ('Cross Dressing', 'Cross Dressing in Uniform and Wash Days'), ('Facial Hair', 'Unwanted Facial Hair'), ('Earrings', 'Wearing of Earrings or Multiple Earrings'), ('Caps', 'Wearing of Caps or Hats inside Covered Facilities'), ('Entering Classroom', 'Entering Classrooms without Permission from Instructor'), ('Leaving Classroom', 'Leaving Classrooms without Permission from Instructor'), ('Attempt Fraternity', 'Attempting to Join a Fraternity'), ('Posting Materials', 'Unauthorized Posting Printed Materials'), ('Use of University Facilities', 'Unauthorized Use of University Facilities'), ('Official Notices', 'Unauthorized Removal of Official Notices and Posters'), ('Gambling', 'Possession of Gambling Paraphernalia'), ('Devices', 'Unauthorized Use of Devices during Class'), ('Resources', 'Irresponsible Use of Water and Electricity within University'), ('Harassment', 'Making Lewd Gestures and Lustful Words to a Student'), ('Property Damage', 'Accidental Damage of University Property'), ('PDA', 'Public Display of Physical Intimacy or Affection'), ('Cigarette', 'Possession of Any type of Cigarette or Tobacco inside University'), ('Liquor/Drugs', 'Liquor and Prohibited Drugs'), ('Illegal Assembly', 'Unauthorized Activities/ Illegal Assemblies'), ('Weapons', 'Deadly and Dangerous Weapons'), ('Threats/Coercion', 'Threats/Coercion'), ('Swindling', 'Swindling'), ('Funds Misuse', 'Misuse of/ Failure to Account Funds'), ('Assault/Injury', 'Violence and Physical Assault/Injury'), ('Robbery/Theft', 'Robbery/ Theft'), ('Damage to Property (Major)', 'Damage to Property'), ('Forced Entry', 'Forcible or Unauthorized entry into the TUP premises'), ('Cybercrime', 'Commission of Cyber crimes as defined under R.A. No. 10175'), ('Slander/Libel', 'Slander/Libel/Gossip'), ('Falsification', 'Falsification of documents, records and credentials'), ('Academic Dishonesty', 'Academic Dishonesty'), ('Immoral Acts', 'Immoral Acts'), ('Gambling (Major)', 'Gambling'), ('Misrepresentation', 'False representation or Misrepresentation'), ('Disrespect', 'Acts of Disrespect'), ('Bribery', 'Offering or Giving Bribes'), ('Smoking (Major)', 'Smoking within the University premises of any type of cigarette or tabacco product'), ('Littering', 'Littering within the University premises'), ('Borrowed ID', 'Entering the University premises with a borrowed ID or registration form'), ('Lending ID', 'Leading of ID/ registration form to facilitate the entry of another student into the University premises'), ('4th Minor', 'Commission of the same or any minor offense for the 4th time'), ('Probation Major', 'Commission of major offense while under academic probation'), ('Final Conviction', 'Final conviction of any offense punishable under the Revised Penal Code, special penal laws or ordinances')], max_length=150),
        ),
    ]
