# Generated by Django 5.1.1 on 2025-11-09 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_alter_violation_violation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancerequest',
            name='student_number',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='student_id',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.CreateModel(
            name='AcsoAccre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(121)])),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('tupc_id', models.CharField(max_length=23, validators=[django.core.validators.RegexValidator(message='Student number must match TUPC-XX-XXXXXXXX (4–15 digits at the end).', regex='^TUPC-\\d{2}-[A-Za-z0-9]{4,15}$')])),
                ('contact', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use +63 XXX-XXX-XXXX.', regex='^\\+63\\s(?:\\d{3}-\\d{3}-\\d{4}|\\d{10})$')])),
                ('program', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('client_type', models.CharField(choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government (Employee/Agency)', 'Government (Employee/Agency)')], max_length=40)),
                ('stakeholder', models.CharField(choices=[('TUPC Student', 'TUPC Student'), ('Alumnus', 'Alumnus'), ('Student from other School', 'Student from other School'), ('External Client', 'External Client'), ('Parent/Guardian', 'Parent/Guardian'), ('TUPC Employee', 'TUPC Employee')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'acso_accre',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tupc_id'], name='acso_accre_tupc_id_3de464_idx'), models.Index(fields=['created_at'], name='acso_accre_created_0d40f6_idx'), models.Index(fields=['client_type'], name='acso_accre_client__a35a7c_idx'), models.Index(fields=['stakeholder'], name='acso_accre_stakeho_91346a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(121)])),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('tupc_id', models.CharField(max_length=23, validators=[django.core.validators.RegexValidator(message='Student number must match TUPC-XX-XXXXXXXX (4–15 digits at the end).', regex='^TUPC-\\d{2}-[A-Za-z0-9]{4,15}$')])),
                ('contact', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use +63 XXX-XXX-XXXX.', regex='^\\+63\\s(?:\\d{3}-\\d{3}-\\d{4}|\\d{10})$')])),
                ('program', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('client_type', models.CharField(choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government (Employee/Agency)', 'Government (Employee/Agency)')], max_length=40)),
                ('stakeholder', models.CharField(choices=[('TUPC Student', 'TUPC Student'), ('Alumnus', 'Alumnus'), ('Student from other School', 'Student from other School'), ('External Client', 'External Client'), ('Parent/Guardian', 'Parent/Guardian'), ('TUPC Employee', 'TUPC Employee')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_assist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tupc_id'], name='student_ass_tupc_id_5b03ad_idx'), models.Index(fields=['created_at'], name='student_ass_created_bc8917_idx'), models.Index(fields=['client_type'], name='student_ass_client__0de6f5_idx'), models.Index(fields=['stakeholder'], name='student_ass_stakeho_4e737f_idx')],
            },
        ),
    ]
