# Generated by Django 5.1.1 on 2025-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0084_alter_clearancerequest_student_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsoaccre',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='studentassist',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='acsoaccre',
            name='client_type',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government (Employee/Agency)', 'Government (Employee/Agency)'), ('TUPC Student - 1st Year', 'TUPC Student - 1st Year'), ('TUPC Student - 2nd Year', 'TUPC Student - 2nd Year'), ('TUPC Student - 3rd Year', 'TUPC Student - 3rd Year'), ('TUPC Student - 4th Year', 'TUPC Student - 4th Year'), ('TUPC Student - 5th Year', 'TUPC Student - 5th Year')], max_length=40),
        ),
        migrations.AlterField(
            model_name='studentassist',
            name='client_type',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government (Employee/Agency)', 'Government (Employee/Agency)'), ('TUPC Student - 1st Year', 'TUPC Student - 1st Year'), ('TUPC Student - 2nd Year', 'TUPC Student - 2nd Year'), ('TUPC Student - 3rd Year', 'TUPC Student - 3rd Year'), ('TUPC Student - 4th Year', 'TUPC Student - 4th Year'), ('TUPC Student - 5th Year', 'TUPC Student - 5th Year')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='acsoaccre',
            index=models.Index(fields=['contact_email'], name='acso_accre_contact_99d33c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassist',
            index=models.Index(fields=['contact_email'], name='student_ass_contact_1d8859_idx'),
        ),
    ]
