# Generated by Django 5.1.1 on 2025-11-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0085_acsoaccre_contact_email_studentassist_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsoaccre',
            name='acso',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='acsoaccre',
            name='client_type',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government (Employee/Agency)', 'Government (Employee/Agency)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='acsoaccre',
            name='stakeholder',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='studentassist',
            name='client_type',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government (Employee/Agency)', 'Government (Employee/Agency)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='studentassist',
            name='stakeholder',
            field=models.CharField(max_length=40),
        ),
    ]
