# Generated by Django 5.1.1 on 2025-11-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0086_acsoaccre_acso_alter_acsoaccre_client_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['role', 'is_active'], name='user_accoun_role_cfeac4_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'admin')), fields=('role',), name='one_active_admin_only'),
        ),
    ]
