# Generated by Django 5.1.1 on 2025-11-16 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0088_alter_violation_violation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='faculty_id',
            field=models.CharField(db_index=True, help_text='Format: NN-NNN (e.g., 12-345)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Use format NN-NNN (e.g., 12-345). Only digits with a hyphen.', regex='^\\d{2}-\\d{3}$')]),
        ),
    ]
