# Generated by Django 5.1.1 on 2025-11-16 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0089_alter_facilitator_faculty_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facilitator',
            name='faculty_id_nn_nnn_format',
        ),
        migrations.AddConstraint(
            model_name='facilitator',
            constraint=models.CheckConstraint(condition=models.Q(('faculty_id__regex', '^\\d{2}-\\d{3,4}$')), name='faculty_id_nn_nnn_format'),
        ),
    ]
