# Generated by Django 5.1.1 on 2025-11-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0091_alter_facilitator_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='title',
            field=models.CharField(blank=True, help_text="Shown on certificates (e.g. 'Head, Office of Student Affairs')", max_length=128, null=True),
        ),
    ]
