# Generated by Django 5.1.1 on 2025-11-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0093_archived_account_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='apology_letter',
            field=models.ImageField(blank=True, null=True, upload_to='apology_letters/'),
        ),
    ]
